# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = '$all'

[character]
success_symbol = "[➟](bold green)"
error_symbol = "[➟](bold red)"

[line_break]
disabled = true


[bun]
format = '(via [$symbol($version )]($style))'

[c]
format = '(via [$symbol($version(-$name) )]($style))'

[cpp]
format = '(via [$symbol($version(-$name) )]($style))'

[cmake]
format = '(via [$symbol($version )]($style))'

[dart]
format = '(via [ ($version )]($style))'

[deno]
format = '(via [ ($version )]($style))'

[directory]
truncate_to_repo = true
home_symbol = "~"
read_only_style = "red"
read_only = " 󰌾"
format = "[$path]($style)[$read_only]($read_only_style) "

[dotnet]
format = '(via [$symbol($version )($style))'

[elixir]
symbol = ' '
format = '(via [$symbol($version )]($style))'

[elm]
format = '(via [$symbol($version )]($style))'

[erlang]
format = '(via [$symbol($version )]($style))'

[fennel]
symbol = ' '
format = '(via [$symbol($version )]($style))'

[golang]
symbol = ' '
format = '(via [$symbol($version )]($style))'

[helm]
symbol = ' '
format = '(via [$symbol($version )]($style))'

[java]
symbol = ' '
format = '(via [$symbol($version )]($style))'

[kotlin]
symbol = ' '
format = '(via [$symbol($version )]($style))'

[lua]
format = '(via [$symbol($version )]($style))'

[nodejs]
format = '(via [$symbol($version )]($style))'

[package]
symbol = ' '
format = '(is [$symbol$version]($style) )'
disabled = true

[php]
symbol = ' '
format = '(via [$symbol($version )]($style))'

[purescript]
format = '(via [$symbol($version )]($style))'

[python]
symbol = ' '
format = '(via [${symbol}$(${version} )(\($virtualenv\) )]($style))'

[ruby]
symbol = ' '
format = '(via [$symbol($version )]($style))'

[rust]
symbol = ' '
format = '(via [$symbol($version )]($style))'

[swift]
format = '(via [$symbol($version )]($style))'

[zig]
symbol = ' '
format = '(via [$symbol($version )]($style))'
