[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]

[[language]]
name = "go"
language-servers = ["gopls", "sqls"]
auto-format = true
formatter = {command = "goimports"}

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

[[language]]
name = "html"
auto-format = true
language-servers = ["vscode-html-language-server", "emmet-ls"]
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = ["typescript-language-server"]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = ["typescript-language-server", "emmet-ls"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "jsx"
auto-format = true
language-servers = ["typescript-language-server", "emmet-ls"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }

[language-server.sqls]
command = "sqls"

[[language]]
name = "sql"
language-servers = ["sqls"]
