[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]

[[language]]
name = "sql"
language-servers = ["sqls"]

[[language]]
name = "go"
language-servers = ["gopls", "sqls"]
auto-format = true
formatter = {command = "goimports"}

[[language]]
name = "gotmpl"
scope = "source.gotmpl"
auto-format = false
language-servers = ["gopls","vscode-html-language-server", "emmet-ls"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
roots = [ "package.json", "jsconfig.json" ]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "html"
auto-format = true
language-servers = ["vscode-html-language-server", "emmet-ls"]
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
roots = [ "package.json", "jsconfig.json" ]
language-servers = ["typescript-language-server"]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
language-servers = ["typescript-language-server", "emmet-ls"]
roots = [ "package.json", "jsconfig.json" ]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "jsx"
auto-format = true
language-servers = ["typescript-language-server", "emmet-ls"]
roots = [ "package.json", "jsconfig.json" ]
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }

[language-server.sqls]
command = "sqls"

[language-server.docker-language-server]
command = "docker-language-server"
args = ["start", "--stdio"]

[[language]]
name = "dockerfile"
language-servers = ["docker-language-server"]
# file-types = ["Dockerfile", {glob = "compose.yaml"}, {glob = "compose.yml"}]
auto-format = true

[language-server.yaml-language-server]
command = "yaml-language-server"
args = ["--stdio"]

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
language-servers = [ "yaml-language-server" ]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }
