[colors.primary]
background = "#18181b" # bg0
foreground = "#e6e6e8" # fg0

[colors.cursor]
text = "#18181b"       # bg0
cursor = "#68f3ca"     # selection0

[colors.selection]
text = "#e6e6e8"       # fg0
background = "#2e403b" # selection1

[colors.normal]
black   = "#222225"    # bg1
red     = "#cd5c60"    # error
green   = "#6fb593"    # green0
yellow  = "#dbac66"    # warn
blue    = "#968cc7"    # ultramarine4_dark
magenta = "#766884"    # violet7
cyan    = "#4d9391"    # hint
white   = "#adadb9"    # fg1

[colors.bright]
black   = "#303035"    # bg2
red     = "#cd9575"    # type
green   = "#68f3ca"    # selection0
yellow  = "#ab98b5"    # constant
blue    = "#80bcb6"    # info
magenta = "#766884"    # violet7
cyan    = "#919a9c"    # gray1
white   = "#e6e6e8"    # fg0

[colors]
draw_bold_text_with_bright_colors = true
