# Kansō-Ink inspired Helix Theme

# Diagnostics
warning = { fg = "orange" }
error   = { fg = "red" }
info    = { fg = "info" }
hint    = { fg = "hint" }
"diagnostic.error" = { underline = { style = "curl", color = "red" } }
"diagnostic.warning" = { underline = { style = "curl", color = "yellow"} }
"diagnostic.info" = { underline = { style = "curl", color = "info"} }
"diagnostic.hint" = { underline = { style = "curl", color = "hint" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

# UI Colors
"ui.background"       = "bg"
"ui.window"           = "bg_alt"
"ui.gutter"           = "bg_alt"
"ui.text"             = "fg"
"ui.text.focus"       = "fg_bright"
"ui.text.info"        = "blue"
"ui.cursor"           = {modifiers = ["reversed"]}
# "ui.cursor.primary"   = {fg = "bg", bg = "cursor", modifiers = ["bold"]}
"ui.cursor.insert"    = "green"
"ui.cursor.select"    = "rose"
"ui.cursor.match"     = "blue"
"ui.selection"        = {bg = "selection"}
"ui.selection.primary"= {bg = "selection"}
"ui.linenr"           = "gray"
"ui.linenr.selected"  = "fg"
"ui.virtual"          = "dim"
"ui.virtual.ruler"    = "dim"
"ui.virtual.whitespace" = "dim"
"ui.statusline"         = {fg = "blue", bg = "bg_alt"}
"ui.statusline.active"  = "gray"
"ui.statusline.inactive"= "dim"
"ui.statusline.normal" = { bg = "blue", fg = "bg", modifiers = ["bold"] }
"ui.statusline.insert" = { bg = "green", fg = "bg", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "rose", fg = "bg", modifiers = ["bold"] }
"ui.help"      = {fg = "blue", bg = "bg_alt"}
"ui.highlight" = "highlight"
"ui.menu"         = {fg = "blue", bg = "bg_alt"}
"ui.menu.selected"= { fg = "fg_bright", bg = "gray" }
"ui.popup"      = {fg = "blue" , bg = "bg_alt"}
"ui.popup.info" = "blue"
"ui.bufferline" = { fg = "gray"}
"ui.bufferline.active" = { fg = "blue", underline = { color = "blue", style = "line" }, modifiers = [ "bold" ] }

# Syntax
"keyword"                     = {fg = "blue", modifiers = ["bold"]}
"function"           = "cyan"
"function.builtin"   = "cyan"
"function.method"    = "cyan"
"function.special"   = "cyan"
"type"              = {fg = "cyan", modifiers = ["bold"]}
"type.builtin"      = {fg = "cyan", modifiers = ["bold"]}
"type.enum.variant" = "orange"
"constructor"       = "cyan"
"constant"                 = "orange"
"constant.numeric"         = "rose"
"constant.character"       = "green"
"constant.character.escape"= "blue"
"constant.builtin.boolean" = "orange"
"string"             = "green"
"string.regexp"      = "orange"
"string.special"     = "yellow"
"string.special.path"= "cyan"
"string.special.url" = "cyan"
"string.special.symbol" = "rose"
"comment" = { fg = "dim", modifiers = ["italic"] }
"variable"             = "fg"
"variable.builtin"     = "blue"
"variable.parameter"   = "fg"
"variable.other.member"= "fg"
"label" = "orange"
"punctuation"            = "operator"
"punctuation.delimiter"  = "operator"
"punctuation.bracket"    = "fg"
"operator" = {fg = "blue", modifiers = ["bold"]}

# Markup
"markup.heading.1" = "blue"
"markup.heading.2" = "cyan"
"markup.heading.3" = "blue"
"markup.heading.4" = "blue"
"markup.heading.5" = "orange"
"markup.heading.6" = "green"
"markup.heading.marker" = "gray"
"markup.list" = {fg = "operator"}
"markup.bold"    = { fg = "fg", modifiers = ["bold"] }
"markup.italic"  = { fg = "fg", modifiers = ["italic"] }
"markup.link"     = "cyan"
"markup.link.url" = "blue"
"markup.link.label" = "cyan"
"markup.link.text"  = "cyan"
"markup.quote"         = "blue"
"markup.raw"           = "fg"
"markup.raw.block"     = "fg"
"markup.raw.inline"    = "fg"
"markup.raw.inline.completion" = "fg"
"markup.raw.inline.hover"      = "fg"

# Diff
"diff.plus"        = "green"
"diff.minus"       = "red"
"diff.delta"       = "yellow"
"diff.delta.moved" = "orange"

# Palette
[palette]
bg         = "#1F2428"
bg_alt     = "#191C22"
fg         = "#AEAEAE"
fg_bright  = "#ECEFF4"
comment  = "#75797F"
type = "#A38ABA"
type_alt = "#69B38E"
operator   = "#9E9B93"
cursor     = "#A3BE8C"
selection  = "#4C566A"
highlight  = "#434C5E"
dim        = "#3B4252"
gray       = "#4C566A"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
rose    = "#D6ACB1"
cyan       = "#8FBCBB"
orange     = "#D08770"
info = "#0db9d7"
hint = "#1abc9c"

